Repository pagopa/pagopa-ecommerce-transactions-scheduler-service, pull requests merged in 2023-06, with the labels that each got.

#30 feat: update commons version
  pom.xml
Labels: enhancement, size/small

#31 feat(common): update common for view name
  pom.xml
Labels: size/small

#32 feat: await sendPaymentResult transaction expiration check
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/EventPublisher.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisher.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzer.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisherTests.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzerTests.kt
  src/test/resources/application-tests.properties
Labels: enhancement, size/small

#34 [CHK-1636] update common version
  pom.xml
Labels: size/small

#35 feat: update commons version
  pom.xml
Labels: enhancement, size/small

#38 feat(logging): format log in ecs json format
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/resources/logback-spring.xml
Labels: enhancement, size/small

#37 Chk 1647 events ttl
  README.md
  helm/values-prod.yaml
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/EventPublisher.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisher.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisherTests.kt
Labels: bug, size/small

#36 [CHK-1653] update all connection string refs
  .env.example
  .env.intellij.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/AzureStorageConfig.kt
  src/main/resources/application.properties
  src/test/resources/application-tests.properties
Labels: enhancement, size/small
