Repository pagopa/pagopa-ecommerce-transactions-scheduler-service, pull requests merged in 2023-03, with the labels that each got.

#2 feat: readme + refactoring batch class package
  README.md
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/scheduledperations/PendingTransactionBatch.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/scheduledperations/PendingTransactionBatchTests.kt
Labels: size/small, ignore-for-release

#3 feat: upgrade commons version handling new statuses
  README.md
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzer.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzerTests.kt
Labels: enhancement

#4 feat: upgrade commons version + expiration queue configuration
  helm/values-dev.yaml
  helm/values-uat.yaml
  pom.xml
Labels: enhancement, size/small

#5 feat: upgrade commons version
  README.md
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzer.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzerTests.kt
Labels: enhancement, size/small

#6 feat: update deploy pipelines
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/chart-github-release.yml
  .devops/azure-templates/helm-microservice-chart-deploy.yml
  .devops/deploy-pipelines.yml
Labels: enhancement, size/large

#8 feat(commons): update commons version
  .java-version
  pom.xml
Labels: size/small
