Repository pagopa/pagopa-ecommerce-transactions-scheduler-service, pull requests merged in 2023-05, with the labels that each got.

#13 fix: update commons version
  pom.xml
Labels: enhancement, size/small

#14 feat: add elk agent
  Dockerfile
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: enhancement, size/small

#15 update commons version 0.13.0
  pom.xml
Labels: enhancement, size/small

#16 feat: update commons version
  pom.xml
Labels: enhancement, size/small

#18 fix: update commons version
  pom.xml
Labels: enhancement, size/small

#17 feat: mongo read preference mode
  src/main/resources/application.properties
Labels: enhancement, size/small

#19 fix: handle expired not authorized status
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/EventPublisher.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisher.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzer.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisherTests.kt
Labels: bug

#20 Chk 1517 handle cancellation requested status
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisher.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisherTests.kt
Labels: bug

#22 fix: handle expiration status for transaction in closure error
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisher.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisherTests.kt
Labels: bug

#23 CHK-579-banner
  src/main/resources/application.properties
  src/main/resources/banner.txt
Labels: enhancement, size/small

#24 feat(helm): CHK-1539 Add helm value for prod
  helm/values-prod.yaml
Labels: enhancement, size/small

#25 fix: update commons version
  pom.xml
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisherTests.kt
Labels: enhancement, size/small

#26 fix: add kubectl installer deploy pipelines
  .devops/deploy-pipelines.yml
Labels: bug, size/small

#28 fix: explicitate eventstore reduce orderby creation date
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/repositories/TransactionsEventStoreRepository.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzer.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzerTests.kt
Labels: enhancement, size/small

#27 fix: add max duration for batch execution
  README.md
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/scheduledperations/PendingTransactionBatch.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/scheduledperations/PendingTransactionBatchTests.kt
Labels: bug, size/small
