Repository pagopa/pagopa-ecommerce-transactions-scheduler-service, pull requests merged in 2023-07, with the labels that each got.

#33 feat(CD): CHK-25-40 Add pipeline for prod
  .devops/azure-templates/chart-current-version.yml
  .devops/deploy-pipelines.yml
Labels: ignore-for-release

#29 CHK-1518: Query pagination
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/EventPublisher.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisher.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/repositories/TransactionsViewRepository.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/scheduledperations/PendingTransactionBatch.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzer.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisherTests.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/scheduledperations/PendingTransactionBatchTests.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzerTests.kt
  src/test/resources/application-tests.properties
Labels: enhancement, size/large

#41 update commons version from 0.18.2. to 0.18.3
  pom.xml
Labels: size/small

#39 CHK-1677 feat(CI): add github action for deploy on PR merge into main branch
  .github/actions/check-pr-semver-labels/action.yml
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/deploy.yml
  README.md
Labels: size/large, skip-release

#43 Fix deploy parameters
  .github/workflows/deploy.yml
Labels: ignore-for-release, chart-patch

#44 fix(deploy-action): fix issue number retrieve code from merge commit
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, ignore-for-release, chart-patch

#45 Deploy trigger fix
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, ignore-for-release, chart-patch

#46 Deploy trigger fix
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, ignore-for-release, chart-patch

#47 fix(check-pr-action):issue number
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, ignore-for-release, chart-patch

#48 fix(check-pr-action): issue number ref
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, ignore-for-release, chart-patch

#49 Deploy trigger fix
  .github/workflows/deploy.yml
Labels: size/small, ignore-for-release, chart-patch

#51 fix(deploy-action): change skipBuild parameter value
  .github/workflows/deploy.yml
Labels: size/small, ignore-for-release, chart-patch

#52 fix(deploy-action): remove apex
  .github/workflows/deploy.yml
Labels: size/small, ignore-for-release, chart-patch

#53 Json formatting
  .github/workflows/deploy.yml
Labels: size/small, ignore-for-release, chart-patch

#54 Json formatting
  .devops/deploy-pipelines.yml
  .github/workflows/deploy.yml
Labels: size/small, skip-release

#57 fix(deploy-action): change json action parameters
  .devops/deploy-pipelines.yml
  .github/workflows/deploy.yml
Labels: size/small, skip-release

#60 [CHK-1566] feat(tracing): use OpenTelemtry agent instead of Elastic APM
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small

#61 fix-pr-number-extraction
  .github/actions/check-pr-semver-labels/action.yml
Labels: size/small, skip-release

#62 feat(dependencies): update commons version
  pom.xml
Labels: size/small, chart-minor, minor

#63 feat(dependencies): update commons version
  pom.xml
Labels: size/small, patch, chart-patch
