Repository pagopa/pagopa-ecommerce-transactions-scheduler-service, pull requests merged in 2024-09, with the labels that each got.

#139 [CHK-3162] Update eventstore deadletter
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/QueuesConsumerConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/deadletter/NotificationDeadLetterConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/deadletter/TransactionDeadLetterConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/deadletter/common.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/TransactionInfoService.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/TransactionSchedulerTestUtil.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/deadletter/NotificationDeadLetterConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/deadletter/TransactionDeadLetterConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/TransactionInfoServiceTest.kt
Labels: size/small, chart-minor, minor

#142 [CHK-3168] Adding data details on trninfo
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/NpgPspsApiKeyConfigBuilder.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/PaymentGatewayConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/exceptions/exceptions.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/TransactionInfoService.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/utils/orderUtils.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/deadletter/NotificationDeadLetterConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/deadletter/TransactionDeadLetterConsumerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/TransactionInfoServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/utils/TransactionInfoUtils.kt
  src/test/resources/application-tests.properties
Labels: size/large, chart-minor, minor

#144 hotfix: remove env variable apple pay psp from helm values prod
  helm/values-prod.yaml
Labels: size/small, patch, chart-patch
