Repository pagopa/pagopa-ecommerce-transactions-scheduler-service, pull requests merged in 2025-01, with the labels that each got.

#157 feat(zero-downtime-deploy): redis integration
  .devops/deploy-pipelines.yml
  .env.example
  .env.intellij.example
  README.md
  command-postman-collection/commands.postman_collection.json
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/ControlBusConfiguration.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/QueuesConsumerConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/RedisStreamEventControllerConfigs.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/EventDispatcherCommandsTemplateWrapper.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/EventDispatcherReceiverStatusTemplateWrapper.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/RedisConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/StreamConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/controller/EventReceiversApiController.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverService.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverStatusPoller.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/InboundChannelAdapterLifecycleHandlerService.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/RedisStreamConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/commands/EventDispatcherGenericCommand.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/commands/EventDispatcherReceiverCommand.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/validation/BeanValidationConfiguration.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/validation/CustomLocalValidatorFactoryBean.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/validation/SuspendAwareKotlinParameterNameDiscoverer.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/controller/EventReceiversApiControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverStatusPollerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/InboundChannelAdapterLifecycleHandlerServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/RedisStreamConsumerTest.kt
  src/test/resources/application-tests.properties
Labels: size/large

#156 feat(zero-downtime-deploy): openapi for receiver stop/start
  .devops/deploy-pipelines.yml
  .env.example
  .env.intellij.example
  Dockerfile
  README.md
  api-spec/scheduler-service-api.yaml
  command-postman-collection/commands.postman_collection.json
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/ControlBusConfiguration.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/QueuesConsumerConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/RedisStreamEventControllerConfigs.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/EventDispatcherCommandsTemplateWrapper.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/EventDispatcherReceiverStatusTemplateWrapper.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/RedisConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/StreamConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/controller/EventReceiversApiController.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/controller/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/exceptions/exceptions.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/repositories/redis/eventreceivers/ReceiverStatus.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/repositories/redis/eventreceivers/ReceiversStatus.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/repositories/redis/eventreceivers/Status.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverService.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverStatusPoller.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/InboundChannelAdapterLifecycleHandlerService.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/RedisStreamConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/commands/EventDispatcherGenericCommand.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/commands/EventDispatcherReceiverCommand.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/validation/BeanValidationConfiguration.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/validation/CustomLocalValidatorFactoryBean.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/validation/SuspendAwareKotlinParameterNameDiscoverer.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/controller/EventReceiversApiControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverStatusPollerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/InboundChannelAdapterLifecycleHandlerServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/RedisStreamConsumerTest.kt
  src/test/resources/application-tests.properties
Labels: size/small, chart-minor, minor

#164 feat (zero downtime deploy) - event receivers programmatic stop/start
  .devops/deploy-pipelines.yml
  .env.example
  .env.intellij.example
  Dockerfile
  README.md
  api-spec/scheduler-service-api.yaml
  command-postman-collection/commands.postman_collection.json
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/ControlBusConfiguration.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/QueuesConsumerConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/RedisStreamEventControllerConfigs.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/EventDispatcherCommandsTemplateWrapper.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/EventDispatcherReceiverStatusTemplateWrapper.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/RedisConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/configurations/redis/StreamConfig.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/controller/EventReceiversApiController.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/controller/exceptionhandler/ExceptionHandler.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/exceptions/exceptions.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/repositories/redis/eventreceivers/ReceiverStatus.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/repositories/redis/eventreceivers/ReceiversStatus.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/repositories/redis/eventreceivers/Status.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverService.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverStatusPoller.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/InboundChannelAdapterLifecycleHandlerService.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/RedisStreamConsumer.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/commands/EventDispatcherGenericCommand.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/commands/EventDispatcherReceiverCommand.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/validation/BeanValidationConfiguration.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/validation/CustomLocalValidatorFactoryBean.kt
  src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/validation/SuspendAwareKotlinParameterNameDiscoverer.kt
  src/main/resources/application.properties
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/controller/EventReceiversApiControllerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/EventReceiverStatusPollerTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/InboundChannelAdapterLifecycleHandlerServiceTest.kt
  src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/streams/RedisStreamConsumerTest.kt
  src/test/resources/application-tests.properties
Labels: size/large, chart-minor, minor

#167 fix: ingress value for UAT
  helm/values-uat.yaml
Labels: size/small, patch, chart-patch

#162 feat(zero downtime deploy): CHK-3655 modified deployment pipeline with release staging and prod
  .devops/azure-templates/chart-current-version.yml
  .devops/azure-templates/receivers-commands/polling-receivers-status.yml
  .devops/azure-templates/receivers-commands/send-receiver-command.yml
  .devops/azure-templates/start-receivers.yml
  .devops/azure-templates/stop-receivers.yml
  .devops/deploy-pipelines.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/large, chart-minor, minor
